---
language: ruby
rvm:
  - 2.5


before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -xvzf geckodriver-v0.24.0-linux64.tar.gz
  - rm geckodriver-v0.24.0-linux64.tar.gz
  - chmod +x geckodriver
  - sudo cp geckodriver /usr/local/bin/
#  - sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
#  - sudo apt-get -y install google-chrome-stable
  - wget https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/chromedriver
    #sudo chown root:root /usr/bin/chromedriver
  - sudo chmod +x /usr/bin/chromedriver

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      name: "version"
      script: ruby -e "require './lib/qat/web/version'; raise StandardError.new unless Gem::Specification::load('qat-web.gemspec').version.to_s == QAT::Web::VERSION"
      if: tag IS blank

    - name: "documentation"
      script: bundle exec rake qat:devel:validate_yard_doc
      if: tag IS blank

    - name: "static"
      script: bundle exec rake qat:devel:static_analysis:validation
      if: tag IS blank

    - name: "unit tests"
      script: bundle exec rake qat:devel:tests:run
      if: tag IS blank

    - name: "gem build"
      script: gem build *.gemspec
      if: tag IS blank

    - stage: release
      name: "gem release"
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        gemspec: qat-web.gemspec
        on:
          tags: true
      if: tag IS present