require 'headless'

#Redifinition of the Headless class, which works as a wrapper arround Xvfb.
#@since 1.1.0
class Headless

  #Link to original implemenmtarion of Headless#pick_available_display
  alias_method :old_pick_available_display, :pick_available_display

  #Shuffles the original display set generated by Headless.
  #This makes the display picking random while still using the original avalability check algorithm.
  def pick_available_display(display_set, can_reuse)
    old_pick_available_display display_set.to_a.shuffle, can_reuse
  end
end